# -*- coding: utf-8 -*-
from . import account_move
from . import property_area_measure
from . import property_auction
from . import property_auction_line
from . import property_commission
from . import property_facility
from . import property_image
from . import property_amenity
from . import property_public_service
from . import property_nearby_connectivity
from . import property_property
from . import property_document
from . import property_document_category
from . import property_document_attachment
from . import property_rental
from . import property_sale
from . import property_tag
from . import property_type
from . import property_structure
from . import rental_bill
from . import res_partner
from . import property_list_type
from . import property_list_name
from . import property_list_value
